version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=url_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"