spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5433/url_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update